name: TelegramManager
main: milk.telegram.TelegramManager
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: SW-Team
description: Nukkit에서 TelegramBot을 관리하게 해주는 플러그인
website: https://github.com/SW-Team/TelegramManager
commands: []